Document: hdpage
Title: Debian hdpage Manual
Author: <insert document author here>
Abstract: This manual describes what hdpage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hdpage/hdpage.sgml.gz

Format: postscript
Files: /usr/share/doc/hdpage/hdpage.ps.gz

Format: text
Files: /usr/share/doc/hdpage/hdpage.text.gz

Format: HTML
Index: /usr/share/doc/hdpage/html/index.html
Files: /usr/share/doc/hdpage/html/*.html
